/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* Generated By:JavaCC: Do not edit this line. HeronSqlParserImplConstants.java */
package org.apache.heron.sql.parser.impl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HeronSqlParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int ABS = 2;
  /** RegularExpression Id. */
  int ABSOLUTE = 3;
  /** RegularExpression Id. */
  int ACTION = 4;
  /** RegularExpression Id. */
  int ADA = 5;
  /** RegularExpression Id. */
  int ADD = 6;
  /** RegularExpression Id. */
  int ADMIN = 7;
  /** RegularExpression Id. */
  int AFTER = 8;
  /** RegularExpression Id. */
  int ALL = 9;
  /** RegularExpression Id. */
  int ALLOCATE = 10;
  /** RegularExpression Id. */
  int ALLOW = 11;
  /** RegularExpression Id. */
  int ALWAYS = 12;
  /** RegularExpression Id. */
  int ALTER = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int ANY = 15;
  /** RegularExpression Id. */
  int ARE = 16;
  /** RegularExpression Id. */
  int ARRAY = 17;
  /** RegularExpression Id. */
  int AS = 18;
  /** RegularExpression Id. */
  int ASC = 19;
  /** RegularExpression Id. */
  int ASENSITIVE = 20;
  /** RegularExpression Id. */
  int ASSERTION = 21;
  /** RegularExpression Id. */
  int ASSIGNMENT = 22;
  /** RegularExpression Id. */
  int ASYMMETRIC = 23;
  /** RegularExpression Id. */
  int AT = 24;
  /** RegularExpression Id. */
  int ATOMIC = 25;
  /** RegularExpression Id. */
  int ATTRIBUTE = 26;
  /** RegularExpression Id. */
  int ATTRIBUTES = 27;
  /** RegularExpression Id. */
  int AUTHORIZATION = 28;
  /** RegularExpression Id. */
  int AVG = 29;
  /** RegularExpression Id. */
  int BEFORE = 30;
  /** RegularExpression Id. */
  int BEGIN = 31;
  /** RegularExpression Id. */
  int BERNOULLI = 32;
  /** RegularExpression Id. */
  int BETWEEN = 33;
  /** RegularExpression Id. */
  int BIGINT = 34;
  /** RegularExpression Id. */
  int BINARY = 35;
  /** RegularExpression Id. */
  int BIT = 36;
  /** RegularExpression Id. */
  int BLOB = 37;
  /** RegularExpression Id. */
  int BOOLEAN = 38;
  /** RegularExpression Id. */
  int BOTH = 39;
  /** RegularExpression Id. */
  int BREADTH = 40;
  /** RegularExpression Id. */
  int BY = 41;
  /** RegularExpression Id. */
  int C = 42;
  /** RegularExpression Id. */
  int CALL = 43;
  /** RegularExpression Id. */
  int CALLED = 44;
  /** RegularExpression Id. */
  int CARDINALITY = 45;
  /** RegularExpression Id. */
  int CASCADE = 46;
  /** RegularExpression Id. */
  int CASCADED = 47;
  /** RegularExpression Id. */
  int CASE = 48;
  /** RegularExpression Id. */
  int CAST = 49;
  /** RegularExpression Id. */
  int CATALOG = 50;
  /** RegularExpression Id. */
  int CATALOG_NAME = 51;
  /** RegularExpression Id. */
  int CEIL = 52;
  /** RegularExpression Id. */
  int CEILING = 53;
  /** RegularExpression Id. */
  int CENTURY = 54;
  /** RegularExpression Id. */
  int CHAIN = 55;
  /** RegularExpression Id. */
  int CHAR = 56;
  /** RegularExpression Id. */
  int CHAR_LENGTH = 57;
  /** RegularExpression Id. */
  int CHARACTER = 58;
  /** RegularExpression Id. */
  int CHARACTER_LENGTH = 59;
  /** RegularExpression Id. */
  int CHARACTER_SET_CATALOG = 60;
  /** RegularExpression Id. */
  int CHARACTER_SET_NAME = 61;
  /** RegularExpression Id. */
  int CHARACTER_SET_SCHEMA = 62;
  /** RegularExpression Id. */
  int CHARACTERISTICS = 63;
  /** RegularExpression Id. */
  int CHARACTERS = 64;
  /** RegularExpression Id. */
  int CHECK = 65;
  /** RegularExpression Id. */
  int CLASS_ORIGIN = 66;
  /** RegularExpression Id. */
  int CLOB = 67;
  /** RegularExpression Id. */
  int CLOSE = 68;
  /** RegularExpression Id. */
  int COALESCE = 69;
  /** RegularExpression Id. */
  int COBOL = 70;
  /** RegularExpression Id. */
  int COLLATE = 71;
  /** RegularExpression Id. */
  int COLLATION = 72;
  /** RegularExpression Id. */
  int COLLATION_CATALOG = 73;
  /** RegularExpression Id. */
  int COLLATION_NAME = 74;
  /** RegularExpression Id. */
  int COLLATION_SCHEMA = 75;
  /** RegularExpression Id. */
  int COLLECT = 76;
  /** RegularExpression Id. */
  int COLUMN = 77;
  /** RegularExpression Id. */
  int COLUMN_NAME = 78;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION = 79;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION_CODE = 80;
  /** RegularExpression Id. */
  int COMMIT = 81;
  /** RegularExpression Id. */
  int COMMITTED = 82;
  /** RegularExpression Id. */
  int CONDITION = 83;
  /** RegularExpression Id. */
  int CONDITION_NUMBER = 84;
  /** RegularExpression Id. */
  int CONNECT = 85;
  /** RegularExpression Id. */
  int CONNECTION = 86;
  /** RegularExpression Id. */
  int CONNECTION_NAME = 87;
  /** RegularExpression Id. */
  int CONSTRAINT = 88;
  /** RegularExpression Id. */
  int CONSTRAINT_CATALOG = 89;
  /** RegularExpression Id. */
  int CONSTRAINT_NAME = 90;
  /** RegularExpression Id. */
  int CONSTRAINT_SCHEMA = 91;
  /** RegularExpression Id. */
  int CONSTRAINTS = 92;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 93;
  /** RegularExpression Id. */
  int CONTAINS = 94;
  /** RegularExpression Id. */
  int CONVERT = 95;
  /** RegularExpression Id. */
  int CONTINUE = 96;
  /** RegularExpression Id. */
  int CORR = 97;
  /** RegularExpression Id. */
  int CORRESPONDING = 98;
  /** RegularExpression Id. */
  int COUNT = 99;
  /** RegularExpression Id. */
  int COVAR_POP = 100;
  /** RegularExpression Id. */
  int COVAR_SAMP = 101;
  /** RegularExpression Id. */
  int CREATE = 102;
  /** RegularExpression Id. */
  int CROSS = 103;
  /** RegularExpression Id. */
  int CUBE = 104;
  /** RegularExpression Id. */
  int CUME_DIST = 105;
  /** RegularExpression Id. */
  int CURRENT = 106;
  /** RegularExpression Id. */
  int CURRENT_CATALOG = 107;
  /** RegularExpression Id. */
  int CURRENT_DATE = 108;
  /** RegularExpression Id. */
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 109;
  /** RegularExpression Id. */
  int CURRENT_PATH = 110;
  /** RegularExpression Id. */
  int CURRENT_ROLE = 111;
  /** RegularExpression Id. */
  int CURRENT_SCHEMA = 112;
  /** RegularExpression Id. */
  int CURRENT_TIME = 113;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 114;
  /** RegularExpression Id. */
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 115;
  /** RegularExpression Id. */
  int CURRENT_USER = 116;
  /** RegularExpression Id. */
  int CURSOR = 117;
  /** RegularExpression Id. */
  int CURSOR_NAME = 118;
  /** RegularExpression Id. */
  int CYCLE = 119;
  /** RegularExpression Id. */
  int DATA = 120;
  /** RegularExpression Id. */
  int DATABASE = 121;
  /** RegularExpression Id. */
  int DATE = 122;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_CODE = 123;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_PRECISION = 124;
  /** RegularExpression Id. */
  int DAY = 125;
  /** RegularExpression Id. */
  int DEALLOCATE = 126;
  /** RegularExpression Id. */
  int DEC = 127;
  /** RegularExpression Id. */
  int DECADE = 128;
  /** RegularExpression Id. */
  int DECIMAL = 129;
  /** RegularExpression Id. */
  int DECLARE = 130;
  /** RegularExpression Id. */
  int DEFAULT_KW = 131;
  /** RegularExpression Id. */
  int DEFAULTS = 132;
  /** RegularExpression Id. */
  int DEFERRABLE = 133;
  /** RegularExpression Id. */
  int DEFERRED = 134;
  /** RegularExpression Id. */
  int DEFINED = 135;
  /** RegularExpression Id. */
  int DEFINER = 136;
  /** RegularExpression Id. */
  int DEGREE = 137;
  /** RegularExpression Id. */
  int DELETE = 138;
  /** RegularExpression Id. */
  int DENSE_RANK = 139;
  /** RegularExpression Id. */
  int DEPTH = 140;
  /** RegularExpression Id. */
  int DEREF = 141;
  /** RegularExpression Id. */
  int DERIVED = 142;
  /** RegularExpression Id. */
  int DESCRIBE = 143;
  /** RegularExpression Id. */
  int DESC = 144;
  /** RegularExpression Id. */
  int DESCRIPTION = 145;
  /** RegularExpression Id. */
  int DESCRIPTOR = 146;
  /** RegularExpression Id. */
  int DETERMINISTIC = 147;
  /** RegularExpression Id. */
  int DIAGNOSTICS = 148;
  /** RegularExpression Id. */
  int DISALLOW = 149;
  /** RegularExpression Id. */
  int DISCONNECT = 150;
  /** RegularExpression Id. */
  int DISPATCH = 151;
  /** RegularExpression Id. */
  int DISTINCT = 152;
  /** RegularExpression Id. */
  int DOMAIN = 153;
  /** RegularExpression Id. */
  int DOUBLE = 154;
  /** RegularExpression Id. */
  int DOW = 155;
  /** RegularExpression Id. */
  int DOY = 156;
  /** RegularExpression Id. */
  int DROP = 157;
  /** RegularExpression Id. */
  int DYNAMIC = 158;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION = 159;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION_CODE = 160;
  /** RegularExpression Id. */
  int EACH = 161;
  /** RegularExpression Id. */
  int ELEMENT = 162;
  /** RegularExpression Id. */
  int ELSE = 163;
  /** RegularExpression Id. */
  int END = 164;
  /** RegularExpression Id. */
  int END_EXEC = 165;
  /** RegularExpression Id. */
  int EPOCH = 166;
  /** RegularExpression Id. */
  int EQUALS = 167;
  /** RegularExpression Id. */
  int ESCAPE = 168;
  /** RegularExpression Id. */
  int EVERY = 169;
  /** RegularExpression Id. */
  int EXCEPT = 170;
  /** RegularExpression Id. */
  int EXCEPTION = 171;
  /** RegularExpression Id. */
  int EXCLUDE = 172;
  /** RegularExpression Id. */
  int EXCLUDING = 173;
  /** RegularExpression Id. */
  int EXEC = 174;
  /** RegularExpression Id. */
  int EXECUTE = 175;
  /** RegularExpression Id. */
  int EXISTS = 176;
  /** RegularExpression Id. */
  int EXP = 177;
  /** RegularExpression Id. */
  int EXPLAIN = 178;
  /** RegularExpression Id. */
  int EXTERNAL = 179;
  /** RegularExpression Id. */
  int EXTEND = 180;
  /** RegularExpression Id. */
  int EXTRACT = 181;
  /** RegularExpression Id. */
  int FALSE = 182;
  /** RegularExpression Id. */
  int FETCH = 183;
  /** RegularExpression Id. */
  int FILTER = 184;
  /** RegularExpression Id. */
  int FINAL = 185;
  /** RegularExpression Id. */
  int FIRST = 186;
  /** RegularExpression Id. */
  int FIRST_VALUE = 187;
  /** RegularExpression Id. */
  int FLOAT = 188;
  /** RegularExpression Id. */
  int FLOOR = 189;
  /** RegularExpression Id. */
  int FOLLOWING = 190;
  /** RegularExpression Id. */
  int FOR = 191;
  /** RegularExpression Id. */
  int FOREIGN = 192;
  /** RegularExpression Id. */
  int FORTRAN = 193;
  /** RegularExpression Id. */
  int FOUND = 194;
  /** RegularExpression Id. */
  int FRAC_SECOND = 195;
  /** RegularExpression Id. */
  int FREE = 196;
  /** RegularExpression Id. */
  int FROM = 197;
  /** RegularExpression Id. */
  int FULL = 198;
  /** RegularExpression Id. */
  int FUNCTION = 199;
  /** RegularExpression Id. */
  int FUSION = 200;
  /** RegularExpression Id. */
  int G = 201;
  /** RegularExpression Id. */
  int GENERAL = 202;
  /** RegularExpression Id. */
  int GENERATED = 203;
  /** RegularExpression Id. */
  int GET = 204;
  /** RegularExpression Id. */
  int GLOBAL = 205;
  /** RegularExpression Id. */
  int GO = 206;
  /** RegularExpression Id. */
  int GOTO = 207;
  /** RegularExpression Id. */
  int GRANT = 208;
  /** RegularExpression Id. */
  int GRANTED = 209;
  /** RegularExpression Id. */
  int GROUP = 210;
  /** RegularExpression Id. */
  int GROUPING = 211;
  /** RegularExpression Id. */
  int HAVING = 212;
  /** RegularExpression Id. */
  int HIERARCHY = 213;
  /** RegularExpression Id. */
  int HOLD = 214;
  /** RegularExpression Id. */
  int HOUR = 215;
  /** RegularExpression Id. */
  int IDENTITY = 216;
  /** RegularExpression Id. */
  int IMMEDIATE = 217;
  /** RegularExpression Id. */
  int IMPLEMENTATION = 218;
  /** RegularExpression Id. */
  int IMPORT = 219;
  /** RegularExpression Id. */
  int IN = 220;
  /** RegularExpression Id. */
  int INDICATOR = 221;
  /** RegularExpression Id. */
  int INCLUDING = 222;
  /** RegularExpression Id. */
  int INCREMENT = 223;
  /** RegularExpression Id. */
  int INITIALLY = 224;
  /** RegularExpression Id. */
  int INNER = 225;
  /** RegularExpression Id. */
  int INOUT = 226;
  /** RegularExpression Id. */
  int INPUT = 227;
  /** RegularExpression Id. */
  int INSENSITIVE = 228;
  /** RegularExpression Id. */
  int INSERT = 229;
  /** RegularExpression Id. */
  int INSTANCE = 230;
  /** RegularExpression Id. */
  int INSTANTIABLE = 231;
  /** RegularExpression Id. */
  int INT = 232;
  /** RegularExpression Id. */
  int INTEGER = 233;
  /** RegularExpression Id. */
  int INTERSECT = 234;
  /** RegularExpression Id. */
  int INTERSECTION = 235;
  /** RegularExpression Id. */
  int INTERVAL = 236;
  /** RegularExpression Id. */
  int INTO = 237;
  /** RegularExpression Id. */
  int INVOKER = 238;
  /** RegularExpression Id. */
  int IS = 239;
  /** RegularExpression Id. */
  int ISOLATION = 240;
  /** RegularExpression Id. */
  int JAVA = 241;
  /** RegularExpression Id. */
  int JOIN = 242;
  /** RegularExpression Id. */
  int JSON = 243;
  /** RegularExpression Id. */
  int K = 244;
  /** RegularExpression Id. */
  int KEY = 245;
  /** RegularExpression Id. */
  int KEY_MEMBER = 246;
  /** RegularExpression Id. */
  int KEY_TYPE = 247;
  /** RegularExpression Id. */
  int LABEL = 248;
  /** RegularExpression Id. */
  int LANGUAGE = 249;
  /** RegularExpression Id. */
  int LARGE = 250;
  /** RegularExpression Id. */
  int LAST = 251;
  /** RegularExpression Id. */
  int LAST_VALUE = 252;
  /** RegularExpression Id. */
  int LATERAL = 253;
  /** RegularExpression Id. */
  int LEADING = 254;
  /** RegularExpression Id. */
  int LEFT = 255;
  /** RegularExpression Id. */
  int LENGTH = 256;
  /** RegularExpression Id. */
  int LEVEL = 257;
  /** RegularExpression Id. */
  int LIBRARY = 258;
  /** RegularExpression Id. */
  int LIKE = 259;
  /** RegularExpression Id. */
  int LIMIT = 260;
  /** RegularExpression Id. */
  int LN = 261;
  /** RegularExpression Id. */
  int LOCAL = 262;
  /** RegularExpression Id. */
  int LOCALTIME = 263;
  /** RegularExpression Id. */
  int LOCALTIMESTAMP = 264;
  /** RegularExpression Id. */
  int LOCATOR = 265;
  /** RegularExpression Id. */
  int LOWER = 266;
  /** RegularExpression Id. */
  int M = 267;
  /** RegularExpression Id. */
  int MAP = 268;
  /** RegularExpression Id. */
  int MATCH = 269;
  /** RegularExpression Id. */
  int MATCHED = 270;
  /** RegularExpression Id. */
  int MAX = 271;
  /** RegularExpression Id. */
  int MAXVALUE = 272;
  /** RegularExpression Id. */
  int MEMBER = 273;
  /** RegularExpression Id. */
  int MERGE = 274;
  /** RegularExpression Id. */
  int MESSAGE_LENGTH = 275;
  /** RegularExpression Id. */
  int MESSAGE_OCTET_LENGTH = 276;
  /** RegularExpression Id. */
  int MESSAGE_TEXT = 277;
  /** RegularExpression Id. */
  int METHOD = 278;
  /** RegularExpression Id. */
  int MICROSECOND = 279;
  /** RegularExpression Id. */
  int MILLENNIUM = 280;
  /** RegularExpression Id. */
  int MIN = 281;
  /** RegularExpression Id. */
  int MINUTE = 282;
  /** RegularExpression Id. */
  int MINVALUE = 283;
  /** RegularExpression Id. */
  int MOD = 284;
  /** RegularExpression Id. */
  int MODIFIES = 285;
  /** RegularExpression Id. */
  int MODULE = 286;
  /** RegularExpression Id. */
  int MONTH = 287;
  /** RegularExpression Id. */
  int MORE_KW = 288;
  /** RegularExpression Id. */
  int MULTISET = 289;
  /** RegularExpression Id. */
  int MUMPS = 290;
  /** RegularExpression Id. */
  int NAME = 291;
  /** RegularExpression Id. */
  int NAMES = 292;
  /** RegularExpression Id. */
  int NATIONAL = 293;
  /** RegularExpression Id. */
  int NATURAL = 294;
  /** RegularExpression Id. */
  int NCHAR = 295;
  /** RegularExpression Id. */
  int NCLOB = 296;
  /** RegularExpression Id. */
  int NESTING = 297;
  /** RegularExpression Id. */
  int NEW = 298;
  /** RegularExpression Id. */
  int NEXT = 299;
  /** RegularExpression Id. */
  int NO = 300;
  /** RegularExpression Id. */
  int NONE = 301;
  /** RegularExpression Id. */
  int NORMALIZE = 302;
  /** RegularExpression Id. */
  int NORMALIZED = 303;
  /** RegularExpression Id. */
  int NOT = 304;
  /** RegularExpression Id. */
  int NULL = 305;
  /** RegularExpression Id. */
  int NULLABLE = 306;
  /** RegularExpression Id. */
  int NULLIF = 307;
  /** RegularExpression Id. */
  int NULLS = 308;
  /** RegularExpression Id. */
  int NUMBER = 309;
  /** RegularExpression Id. */
  int NUMERIC = 310;
  /** RegularExpression Id. */
  int OBJECT = 311;
  /** RegularExpression Id. */
  int OCTET_LENGTH = 312;
  /** RegularExpression Id. */
  int OCTETS = 313;
  /** RegularExpression Id. */
  int OF = 314;
  /** RegularExpression Id. */
  int OFFSET = 315;
  /** RegularExpression Id. */
  int OLD = 316;
  /** RegularExpression Id. */
  int ON = 317;
  /** RegularExpression Id. */
  int ONLY = 318;
  /** RegularExpression Id. */
  int OPEN = 319;
  /** RegularExpression Id. */
  int OPTION = 320;
  /** RegularExpression Id. */
  int OPTIONS = 321;
  /** RegularExpression Id. */
  int OR = 322;
  /** RegularExpression Id. */
  int ORDER = 323;
  /** RegularExpression Id. */
  int ORDERING = 324;
  /** RegularExpression Id. */
  int ORDINALITY = 325;
  /** RegularExpression Id. */
  int OTHERS = 326;
  /** RegularExpression Id. */
  int OUT = 327;
  /** RegularExpression Id. */
  int OUTER = 328;
  /** RegularExpression Id. */
  int OUTPUT = 329;
  /** RegularExpression Id. */
  int OVER = 330;
  /** RegularExpression Id. */
  int OVERLAPS = 331;
  /** RegularExpression Id. */
  int OVERLAY = 332;
  /** RegularExpression Id. */
  int OVERRIDING = 333;
  /** RegularExpression Id. */
  int PAD = 334;
  /** RegularExpression Id. */
  int PARAMETER = 335;
  /** RegularExpression Id. */
  int PARAMETER_MODE = 336;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 337;
  /** RegularExpression Id. */
  int PARAMETER_ORDINAL_POSITION = 338;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_CATALOG = 339;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_NAME = 340;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_SCHEMA = 341;
  /** RegularExpression Id. */
  int PARTIAL = 342;
  /** RegularExpression Id. */
  int PARTITION = 343;
  /** RegularExpression Id. */
  int PASCAL = 344;
  /** RegularExpression Id. */
  int PASSTHROUGH = 345;
  /** RegularExpression Id. */
  int PATH = 346;
  /** RegularExpression Id. */
  int PERCENT_RANK = 347;
  /** RegularExpression Id. */
  int PERCENTILE_CONT = 348;
  /** RegularExpression Id. */
  int PERCENTILE_DISC = 349;
  /** RegularExpression Id. */
  int PLACING = 350;
  /** RegularExpression Id. */
  int PLAN = 351;
  /** RegularExpression Id. */
  int PLI = 352;
  /** RegularExpression Id. */
  int POSITION = 353;
  /** RegularExpression Id. */
  int POWER = 354;
  /** RegularExpression Id. */
  int PRECEDING = 355;
  /** RegularExpression Id. */
  int PRECISION = 356;
  /** RegularExpression Id. */
  int PREPARE = 357;
  /** RegularExpression Id. */
  int PRESERVE = 358;
  /** RegularExpression Id. */
  int PRIMARY = 359;
  /** RegularExpression Id. */
  int PRIOR = 360;
  /** RegularExpression Id. */
  int PRIVILEGES = 361;
  /** RegularExpression Id. */
  int PROCEDURE = 362;
  /** RegularExpression Id. */
  int PUBLIC = 363;
  /** RegularExpression Id. */
  int QUARTER = 364;
  /** RegularExpression Id. */
  int RANGE = 365;
  /** RegularExpression Id. */
  int RANK = 366;
  /** RegularExpression Id. */
  int READ = 367;
  /** RegularExpression Id. */
  int READS = 368;
  /** RegularExpression Id. */
  int REAL = 369;
  /** RegularExpression Id. */
  int RECURSIVE = 370;
  /** RegularExpression Id. */
  int REF = 371;
  /** RegularExpression Id. */
  int REFERENCES = 372;
  /** RegularExpression Id. */
  int REFERENCING = 373;
  /** RegularExpression Id. */
  int REGR_AVGX = 374;
  /** RegularExpression Id. */
  int REGR_AVGY = 375;
  /** RegularExpression Id. */
  int REGR_COUNT = 376;
  /** RegularExpression Id. */
  int REGR_INTERCEPT = 377;
  /** RegularExpression Id. */
  int REGR_R2 = 378;
  /** RegularExpression Id. */
  int REGR_SLOPE = 379;
  /** RegularExpression Id. */
  int REGR_SXX = 380;
  /** RegularExpression Id. */
  int REGR_SXY = 381;
  /** RegularExpression Id. */
  int REGR_SYY = 382;
  /** RegularExpression Id. */
  int RELATIVE = 383;
  /** RegularExpression Id. */
  int RELEASE = 384;
  /** RegularExpression Id. */
  int REPEATABLE = 385;
  /** RegularExpression Id. */
  int REPLACE = 386;
  /** RegularExpression Id. */
  int RESET = 387;
  /** RegularExpression Id. */
  int RESTART = 388;
  /** RegularExpression Id. */
  int RESTRICT = 389;
  /** RegularExpression Id. */
  int RESULT = 390;
  /** RegularExpression Id. */
  int RETURN = 391;
  /** RegularExpression Id. */
  int RETURNED_CARDINALITY = 392;
  /** RegularExpression Id. */
  int RETURNED_LENGTH = 393;
  /** RegularExpression Id. */
  int RETURNED_OCTET_LENGTH = 394;
  /** RegularExpression Id. */
  int RETURNED_SQLSTATE = 395;
  /** RegularExpression Id. */
  int RETURNS = 396;
  /** RegularExpression Id. */
  int REVOKE = 397;
  /** RegularExpression Id. */
  int RIGHT = 398;
  /** RegularExpression Id. */
  int ROLE = 399;
  /** RegularExpression Id. */
  int ROLLBACK = 400;
  /** RegularExpression Id. */
  int ROLLUP = 401;
  /** RegularExpression Id. */
  int ROUTINE = 402;
  /** RegularExpression Id. */
  int ROUTINE_CATALOG = 403;
  /** RegularExpression Id. */
  int ROUTINE_NAME = 404;
  /** RegularExpression Id. */
  int ROUTINE_SCHEMA = 405;
  /** RegularExpression Id. */
  int ROW = 406;
  /** RegularExpression Id. */
  int ROW_COUNT = 407;
  /** RegularExpression Id. */
  int ROW_NUMBER = 408;
  /** RegularExpression Id. */
  int ROWS = 409;
  /** RegularExpression Id. */
  int SAVEPOINT = 410;
  /** RegularExpression Id. */
  int SCALE = 411;
  /** RegularExpression Id. */
  int SCHEMA = 412;
  /** RegularExpression Id. */
  int SCHEMA_NAME = 413;
  /** RegularExpression Id. */
  int SCOPE = 414;
  /** RegularExpression Id. */
  int SCOPE_CATALOGS = 415;
  /** RegularExpression Id. */
  int SCOPE_NAME = 416;
  /** RegularExpression Id. */
  int SCOPE_SCHEMA = 417;
  /** RegularExpression Id. */
  int SCROLL = 418;
  /** RegularExpression Id. */
  int SEARCH = 419;
  /** RegularExpression Id. */
  int SECOND = 420;
  /** RegularExpression Id. */
  int SECTION = 421;
  /** RegularExpression Id. */
  int SECURITY = 422;
  /** RegularExpression Id. */
  int SELECT = 423;
  /** RegularExpression Id. */
  int SELF = 424;
  /** RegularExpression Id. */
  int SENSITIVE = 425;
  /** RegularExpression Id. */
  int SEQUENCE = 426;
  /** RegularExpression Id. */
  int SERIALIZABLE = 427;
  /** RegularExpression Id. */
  int SERVER = 428;
  /** RegularExpression Id. */
  int SERVER_NAME = 429;
  /** RegularExpression Id. */
  int SESSION = 430;
  /** RegularExpression Id. */
  int SESSION_USER = 431;
  /** RegularExpression Id. */
  int SET = 432;
  /** RegularExpression Id. */
  int SETS = 433;
  /** RegularExpression Id. */
  int SET_MINUS = 434;
  /** RegularExpression Id. */
  int SIMILAR = 435;
  /** RegularExpression Id. */
  int SIMPLE = 436;
  /** RegularExpression Id. */
  int SIZE = 437;
  /** RegularExpression Id. */
  int SMALLINT = 438;
  /** RegularExpression Id. */
  int SOME = 439;
  /** RegularExpression Id. */
  int SOURCE = 440;
  /** RegularExpression Id. */
  int SPACE = 441;
  /** RegularExpression Id. */
  int SPECIFIC = 442;
  /** RegularExpression Id. */
  int SPECIFIC_NAME = 443;
  /** RegularExpression Id. */
  int SPECIFICTYPE = 444;
  /** RegularExpression Id. */
  int SQL = 445;
  /** RegularExpression Id. */
  int SQLEXCEPTION = 446;
  /** RegularExpression Id. */
  int SQLSTATE = 447;
  /** RegularExpression Id. */
  int SQLWARNING = 448;
  /** RegularExpression Id. */
  int SQL_BIGINT = 449;
  /** RegularExpression Id. */
  int SQL_BINARY = 450;
  /** RegularExpression Id. */
  int SQL_BIT = 451;
  /** RegularExpression Id. */
  int SQL_BLOB = 452;
  /** RegularExpression Id. */
  int SQL_BOOLEAN = 453;
  /** RegularExpression Id. */
  int SQL_CHAR = 454;
  /** RegularExpression Id. */
  int SQL_CLOB = 455;
  /** RegularExpression Id. */
  int SQL_DATE = 456;
  /** RegularExpression Id. */
  int SQL_DECIMAL = 457;
  /** RegularExpression Id. */
  int SQL_DOUBLE = 458;
  /** RegularExpression Id. */
  int SQL_FLOAT = 459;
  /** RegularExpression Id. */
  int SQL_INTEGER = 460;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY = 461;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_HOUR = 462;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_MINUTE = 463;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_SECOND = 464;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR = 465;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR_TO_MINUTE = 466;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR_TO_SECOND = 467;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MINUTE = 468;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MINUTE_TO_SECOND = 469;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MONTH = 470;
  /** RegularExpression Id. */
  int SQL_INTERVAL_SECOND = 471;
  /** RegularExpression Id. */
  int SQL_INTERVAL_YEAR = 472;
  /** RegularExpression Id. */
  int SQL_INTERVAL_YEAR_TO_MONTH = 473;
  /** RegularExpression Id. */
  int SQL_LONGVARBINARY = 474;
  /** RegularExpression Id. */
  int SQL_LONGVARCHAR = 475;
  /** RegularExpression Id. */
  int SQL_LONGVARNCHAR = 476;
  /** RegularExpression Id. */
  int SQL_NCHAR = 477;
  /** RegularExpression Id. */
  int SQL_NCLOB = 478;
  /** RegularExpression Id. */
  int SQL_NUMERIC = 479;
  /** RegularExpression Id. */
  int SQL_NVARCHAR = 480;
  /** RegularExpression Id. */
  int SQL_REAL = 481;
  /** RegularExpression Id. */
  int SQL_SMALLINT = 482;
  /** RegularExpression Id. */
  int SQL_TIME = 483;
  /** RegularExpression Id. */
  int SQL_TIMESTAMP = 484;
  /** RegularExpression Id. */
  int SQL_TINYINT = 485;
  /** RegularExpression Id. */
  int SQL_TSI_DAY = 486;
  /** RegularExpression Id. */
  int SQL_TSI_FRAC_SECOND = 487;
  /** RegularExpression Id. */
  int SQL_TSI_HOUR = 488;
  /** RegularExpression Id. */
  int SQL_TSI_MICROSECOND = 489;
  /** RegularExpression Id. */
  int SQL_TSI_MINUTE = 490;
  /** RegularExpression Id. */
  int SQL_TSI_MONTH = 491;
  /** RegularExpression Id. */
  int SQL_TSI_QUARTER = 492;
  /** RegularExpression Id. */
  int SQL_TSI_SECOND = 493;
  /** RegularExpression Id. */
  int SQL_TSI_WEEK = 494;
  /** RegularExpression Id. */
  int SQL_TSI_YEAR = 495;
  /** RegularExpression Id. */
  int SQL_VARBINARY = 496;
  /** RegularExpression Id. */
  int SQL_VARCHAR = 497;
  /** RegularExpression Id. */
  int SQRT = 498;
  /** RegularExpression Id. */
  int START = 499;
  /** RegularExpression Id. */
  int STATE = 500;
  /** RegularExpression Id. */
  int STATEMENT = 501;
  /** RegularExpression Id. */
  int STATIC = 502;
  /** RegularExpression Id. */
  int STDDEV_POP = 503;
  /** RegularExpression Id. */
  int STDDEV_SAMP = 504;
  /** RegularExpression Id. */
  int STREAM = 505;
  /** RegularExpression Id. */
  int STRUCTURE = 506;
  /** RegularExpression Id. */
  int STYLE = 507;
  /** RegularExpression Id. */
  int SUBCLASS_ORIGIN = 508;
  /** RegularExpression Id. */
  int SUBMULTISET = 509;
  /** RegularExpression Id. */
  int SUBSTRING = 510;
  /** RegularExpression Id. */
  int SUBSTITUTE = 511;
  /** RegularExpression Id. */
  int SUM = 512;
  /** RegularExpression Id. */
  int SYMMETRIC = 513;
  /** RegularExpression Id. */
  int SYSTEM = 514;
  /** RegularExpression Id. */
  int SYSTEM_USER = 515;
  /** RegularExpression Id. */
  int TABLE = 516;
  /** RegularExpression Id. */
  int TABLE_NAME = 517;
  /** RegularExpression Id. */
  int TABLESAMPLE = 518;
  /** RegularExpression Id. */
  int TEMPORARY = 519;
  /** RegularExpression Id. */
  int THEN = 520;
  /** RegularExpression Id. */
  int TIES = 521;
  /** RegularExpression Id. */
  int TIME = 522;
  /** RegularExpression Id. */
  int TIMESTAMP = 523;
  /** RegularExpression Id. */
  int TIMESTAMPADD = 524;
  /** RegularExpression Id. */
  int TIMESTAMPDIFF = 525;
  /** RegularExpression Id. */
  int TIMEZONE_HOUR = 526;
  /** RegularExpression Id. */
  int TIMEZONE_MINUTE = 527;
  /** RegularExpression Id. */
  int TINYINT = 528;
  /** RegularExpression Id. */
  int TO = 529;
  /** RegularExpression Id. */
  int TOP_LEVEL_COUNT = 530;
  /** RegularExpression Id. */
  int TRAILING = 531;
  /** RegularExpression Id. */
  int TRANSACTION = 532;
  /** RegularExpression Id. */
  int TRANSACTIONS_ACTIVE = 533;
  /** RegularExpression Id. */
  int TRANSACTIONS_COMMITTED = 534;
  /** RegularExpression Id. */
  int TRANSACTIONS_ROLLED_BACK = 535;
  /** RegularExpression Id. */
  int TRANSFORM = 536;
  /** RegularExpression Id. */
  int TRANSFORMS = 537;
  /** RegularExpression Id. */
  int TRANSLATE = 538;
  /** RegularExpression Id. */
  int TRANSLATION = 539;
  /** RegularExpression Id. */
  int TREAT = 540;
  /** RegularExpression Id. */
  int TRIGGER = 541;
  /** RegularExpression Id. */
  int TRIGGER_CATALOG = 542;
  /** RegularExpression Id. */
  int TRIGGER_NAME = 543;
  /** RegularExpression Id. */
  int TRIGGER_SCHEMA = 544;
  /** RegularExpression Id. */
  int TRIM = 545;
  /** RegularExpression Id. */
  int TRUE = 546;
  /** RegularExpression Id. */
  int TYPE = 547;
  /** RegularExpression Id. */
  int UESCAPE = 548;
  /** RegularExpression Id. */
  int UNBOUNDED = 549;
  /** RegularExpression Id. */
  int UNCOMMITTED = 550;
  /** RegularExpression Id. */
  int UNDER = 551;
  /** RegularExpression Id. */
  int UNION = 552;
  /** RegularExpression Id. */
  int UNIQUE = 553;
  /** RegularExpression Id. */
  int UNKNOWN = 554;
  /** RegularExpression Id. */
  int UNNAMED = 555;
  /** RegularExpression Id. */
  int UNNEST = 556;
  /** RegularExpression Id. */
  int UPDATE = 557;
  /** RegularExpression Id. */
  int UPPER = 558;
  /** RegularExpression Id. */
  int UPSERT = 559;
  /** RegularExpression Id. */
  int USAGE = 560;
  /** RegularExpression Id. */
  int USER = 561;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CATALOG = 562;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CODE = 563;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_NAME = 564;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_SCHEMA = 565;
  /** RegularExpression Id. */
  int USING = 566;
  /** RegularExpression Id. */
  int VALUE = 567;
  /** RegularExpression Id. */
  int VALUES = 568;
  /** RegularExpression Id. */
  int VAR_POP = 569;
  /** RegularExpression Id. */
  int VAR_SAMP = 570;
  /** RegularExpression Id. */
  int VARCHAR = 571;
  /** RegularExpression Id. */
  int VARBINARY = 572;
  /** RegularExpression Id. */
  int VARYING = 573;
  /** RegularExpression Id. */
  int VERSION = 574;
  /** RegularExpression Id. */
  int VIEW = 575;
  /** RegularExpression Id. */
  int WEEK = 576;
  /** RegularExpression Id. */
  int WHEN = 577;
  /** RegularExpression Id. */
  int WHENEVER = 578;
  /** RegularExpression Id. */
  int WHERE = 579;
  /** RegularExpression Id. */
  int WIDTH_BUCKET = 580;
  /** RegularExpression Id. */
  int WINDOW = 581;
  /** RegularExpression Id. */
  int WITH = 582;
  /** RegularExpression Id. */
  int WITHIN = 583;
  /** RegularExpression Id. */
  int WITHOUT = 584;
  /** RegularExpression Id. */
  int WORK = 585;
  /** RegularExpression Id. */
  int WRAPPER = 586;
  /** RegularExpression Id. */
  int WRITE = 587;
  /** RegularExpression Id. */
  int XML = 588;
  /** RegularExpression Id. */
  int YEAR = 589;
  /** RegularExpression Id. */
  int ZONE = 590;
  /** RegularExpression Id. */
  int APPLY = 591;
  /** RegularExpression Id. */
  int LOCATION = 592;
  /** RegularExpression Id. */
  int INPUTFORMAT = 593;
  /** RegularExpression Id. */
  int OUTPUTFORMAT = 594;
  /** RegularExpression Id. */
  int PARALLELISM = 595;
  /** RegularExpression Id. */
  int STORED = 596;
  /** RegularExpression Id. */
  int TBLPROPERTIES = 597;
  /** RegularExpression Id. */
  int JAR = 598;
  /** RegularExpression Id. */
  int UNSIGNED_INTEGER_LITERAL = 599;
  /** RegularExpression Id. */
  int APPROX_NUMERIC_LITERAL = 600;
  /** RegularExpression Id. */
  int DECIMAL_NUMERIC_LITERAL = 601;
  /** RegularExpression Id. */
  int EXPONENT = 602;
  /** RegularExpression Id. */
  int HEXDIGIT = 603;
  /** RegularExpression Id. */
  int WHITESPACE = 604;
  /** RegularExpression Id. */
  int BINARY_STRING_LITERAL = 605;
  /** RegularExpression Id. */
  int QUOTED_STRING = 606;
  /** RegularExpression Id. */
  int PREFIXED_STRING_LITERAL = 607;
  /** RegularExpression Id. */
  int UNICODE_STRING_LITERAL = 608;
  /** RegularExpression Id. */
  int CHARSETNAME = 609;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_ESCAPE_CHAR = 610;
  /** RegularExpression Id. */
  int LPAREN = 611;
  /** RegularExpression Id. */
  int RPAREN = 612;
  /** RegularExpression Id. */
  int LBRACE_D = 613;
  /** RegularExpression Id. */
  int LBRACE_T = 614;
  /** RegularExpression Id. */
  int LBRACE_TS = 615;
  /** RegularExpression Id. */
  int LBRACE_FN = 616;
  /** RegularExpression Id. */
  int LBRACE = 617;
  /** RegularExpression Id. */
  int RBRACE = 618;
  /** RegularExpression Id. */
  int LBRACKET = 619;
  /** RegularExpression Id. */
  int RBRACKET = 620;
  /** RegularExpression Id. */
  int SEMICOLON = 621;
  /** RegularExpression Id. */
  int DOT = 622;
  /** RegularExpression Id. */
  int COMMA = 623;
  /** RegularExpression Id. */
  int EQ = 624;
  /** RegularExpression Id. */
  int GT = 625;
  /** RegularExpression Id. */
  int LT = 626;
  /** RegularExpression Id. */
  int HOOK = 627;
  /** RegularExpression Id. */
  int COLON = 628;
  /** RegularExpression Id. */
  int LE = 629;
  /** RegularExpression Id. */
  int GE = 630;
  /** RegularExpression Id. */
  int NE = 631;
  /** RegularExpression Id. */
  int NE2 = 632;
  /** RegularExpression Id. */
  int PLUS = 633;
  /** RegularExpression Id. */
  int MINUS = 634;
  /** RegularExpression Id. */
  int STAR = 635;
  /** RegularExpression Id. */
  int SLASH = 636;
  /** RegularExpression Id. */
  int CONCAT = 637;
  /** RegularExpression Id. */
  int NAMED_ARGUMENT_ASSIGNMENT = 638;
  /** RegularExpression Id. */
  int DOUBLE_PERIOD = 639;
  /** RegularExpression Id. */
  int QUOTE = 640;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 641;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 649;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 650;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 651;
  /** RegularExpression Id. */
  int BRACKET_QUOTED_IDENTIFIER = 653;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 654;
  /** RegularExpression Id. */
  int BACK_QUOTED_IDENTIFIER = 655;
  /** RegularExpression Id. */
  int COLLATION_ID = 656;
  /** RegularExpression Id. */
  int IDENTIFIER = 657;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_IDENTIFIER = 658;
  /** RegularExpression Id. */
  int LETTER = 659;
  /** RegularExpression Id. */
  int DIGIT = 660;
  /** RegularExpression Id. */
  int BEL = 661;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DQID = 1;
  /** Lexical state. */
  int BTID = 2;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALWAYS\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONVERT\"",
    "\"CONTINUE\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESCRIBE\"",
    "\"DESC\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTERNAL\"",
    "\"EXTEND\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FREE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOUR\"",
    "\"IDENTITY\"",
    "\"IMMEDIATE\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INDICATOR\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONTH\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSTHROUGH\"",
    "\"PATH\"",
    "\"PERCENT_RANK\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"POSITION\"",
    "\"POWER\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUARTER\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"SAVEPOINT\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSTRING\"",
    "\"SUBSTITUTE\"",
    "\"SUM\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRUE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARCHAR\"",
    "\"VARBINARY\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"ZONE\"",
    "\"APPLY\"",
    "\"LOCATION\"",
    "\"INPUTFORMAT\"",
    "\"OUTPUTFORMAT\"",
    "\"PARALLELISM\"",
    "\"STORED\"",
    "\"TBLPROPERTIES\"",
    "\"JAR\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 647>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 652>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<COLLATION_ID>",
    "<IDENTIFIER>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
